# Generated by Django 2.0.4 on 2018-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
