# Generated by Django 2.0.4 on 2018-04-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='date',
        ),
    ]
