# Generated by Django 2.0.4 on 2018-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180513_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', null=True, to='blog.Tag'),
        ),
    ]
