# Generated by Django 2.0.4 on 2018-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180513_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default=' ', null=True, to='blog.Tag'),
        ),
    ]
